### ISSUE TITLE
No such file or directory error following upgrade to Mac OS X Sierra

### ISSUE THREAD

**Issue by svannoy** [theseal/ssh-askpass#13]
Hi,
I just upgraded to 10.12.2 and started getting error messages when trying to push an update to github via RStudio (latest version, 1.0.136).

The error is:

`ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

I've used the brew instructions on the readme, and brew confirms ssh-askpass is installed. 

Note, there is no /usr/X11R6 directory on  my system, within usr there is just X11 (along with bin, lib, libexec, local, sbin, share, and standalone). X11 is an alias to /opt/X11

I'm a linux novice so I don't really know what is going on. It seems to me that for some reason some task is looking for ssh-askpass in /usr/X11/R6/bin which doesn't exist and I don't know how to tell it to look elsewhere. Thus I don't think this is really a bug with your repository here, but I'm hoping you can help.

Sincerely,
Steven

**Comment by theseal** [comment]
Run `brew update` to make sure that you have latest version. Then it should work if you enabled the ssh-add "homebrew service" (`brew services start theseal/ssh-askpass/ssh-askpass`),  rebooted an then added the key again as described in the [caveats](https://github.com/theseal/homebrew-ssh-askpass/blob/master/Formula/ssh-askpass.rb#L46-L49).

**Comment by svannoy** [comment]
Thanks so much, I had not enabled the ssh-add service, I saw that I needed to but didn’t know how. Your line below:

> brew services start theseal/ssh-askpass/ssh-askpass
> 
> 
Did the trick. I was also confused about the caveat, it seemed like command, `ssh-add -c` would expect an argument. So running those two extra lines with a reboot in between did it.

S

*****************************
@stevenvannoy
https://stevenvannoy.wordpress.com

**Comment by theseal** [comment]
Glad to help! 🙃

Closes #13

**Comment by pom4pom** [comment]
I have similar problem but different application.

I am wondering if I can just create X11R6 dir and link it to X11?

thanks
