### ISSUE TITLE
How does the launching work?

### ISSUE THREAD

**Issue by hmijail** [theseal/ssh-askpass#17]
I'm trying to make ssh-askpass work with ssh-ident, and I'm having a bit of a chicken-and-egg-and-wtf problem. 

[ssh-ident](https://github.com/ccontavalli/ssh-ident) works by intercepting calls to ssh and spawning ssh-agents specific for the identity necessary for the connection that is being established, which then get loaded with only the appropriate public keys.

If this is done in the terminal, ssh-ident works perfectly: the key's password is asked in the terminal when ssh-add loads it, and posterior questions for usage confirmation are handled by ssh-askpass in the GUI. 

However, if the ssh-agent has not been prepared by previous terminal usage, GUI programs using ssh just fail. I understand that this is because ssh-add finds it has no terminal where to ask, and it doesn't try using ssh-askpass. And this is what I'd like to fix.

Now, this seemingly should be fixed by defining SSH_ASKPASS and DISPLAY in the environment where ssh-add runs. And there are patches for ssh-ident to do just that. But it's not working. And the problem seems to be that such variables are actually only defined by the askpass plist launcher. But I don't understand how/when exactly is this launcher being triggered, and how could I define the environment variables earlier.

So, could you explain how does this work? I'm not familiar with launchd nor with how SSH_AUTH_SOCK works, and I'm assuming that it'd be much easier for you to explain the mechanism than for me to dig around until I put together the pieces.

Thank you!

**Comment by simmel** [comment]
See the [launchd.plist(5)](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html)-manpage. Search for `Socket` (sadly, Apple has no anchors on their man-page) and you'll find a description.

**Comment by hmijail** [comment]
Thank you, but I already read that, and it's not helping.

OK, so in case someone else looks for some reference more helpful than the manpages: actually the Launch plist for this ssh-askpass is (misleadingly, I'd say) launching ssh-agent, and so overriding with an user-installed launchd job the on-demand launching of ssh-agent at the system level (/System/Library/LaunchAgents/com.openssh.ssh-agent.plist). Otherwise the mechanism is exactly the same, only setting the SSH_ASKPASS and DISPLAY environment vars.

So it's rather puzzling that ssh-ident actually ends up triggering the GUI dialogs, given that it launches its own ssh-agents. More digging is needed, but in ssh-ident.
