### ISSUE TITLE
macOS 10.13 doesn't have /usr/X11R6 and SIP prevents symbolic linking

### ISSUE THREAD

**Issue by 47ronin** [theseal/ssh-askpass#18]
```
$ sudo ln -s /opt/X11 /usr/X11R6
ln: /usr/X11R6: Operation not permitted
```

Some believe this error occurs because System Integrity Protection is in place.

A few applications that rely on ssh-askpass give the error:
`ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory`

My workaround fails due to inability to create the symbolic link. Can the path instead be changed to something other than /usr/X11R6?

Please see https://github.com/desktop/desktop/issues/852#issuecomment-325437865

**Comment by theseal** [comment]
The old solution base on links is no longer supported (even if still possible by disabling SIP, creating the link and then enabling SIP again). The only supported way to run `ssh-askpass` is to run it through `launchd` preferable through `brew services`.

**Comment by 47ronin** [comment]
One new workaround: System Integrity Protection is a good security feature and doesn't need to be disabled in macOS 10.13+ to keep ssh_askpass working. Steps:

- (Re)install xquartz:
`$ brew reinstall xquartz`

This will *officially* recreate the /usr/X11R6 directory without disturbing SIP.

Next:

```
$ cd /usr/X11R6/bin
$ sudo ln -s /usr/local/bin/ssh-askpass ssh-askpass
```

**Comment by simmel** [comment]
Ah, good to know. Thanks!

**Comment by ximet** [comment]
not working for me

**Comment by simmel** [comment]
@ximet please use the supported way as documented in the README.
