### ISSUE TITLE
Error message printed when hitting cancel

### ISSUE THREAD

**Issue by a-kohout** [theseal/ssh-askpass#19]
I'm using `ssh-askpass` as a helper for `sudo` to graphically prompt for the password like so:
```
SUDO_ASKPASS="$(which ssh-askpass)"
export SUDO_ASKPASS

if (( EUID != 0 )); then
  echo "requesting admin credentials"
  if sudo -v; then
    echo "Ok"
  else
    echo "failed"
    exit 1
  fi
fi
```
This is needed for wrapping scripts with [platypus](http://sveinbjorn.org/platypus), which does not emulate a TTY making STDIN unavailable.
It works great, however when clicking Cancel `ssh-askpass` prints the following error message:
`1176:1286: execution error: Test got an error: User canceled. (-128)`

Wrapping the whole tell application part of the applescript in a try block fixes it for me

```
on run argv
  set args to argv as text
  set frontmost_application to name of (info for (path to frontmost application))
  try
    tell application frontmost_application
      if args ends with ": " or args ends with ":" then
        if args contains "pass" or args contains "pin" then
          display dialog args with icon caution default button "OK" default answer "" with hidden answer
        else
          display dialog args with icon caution default button "OK" default answer ""
        end if
        return result's text returned
      else
        display dialog args with icon caution default button "Cancel"
        return
      end if
    end tell
  on error number -128
    -- don't return error message when user clicks Cancel
  end try
end run
```

**Comment by theseal** [comment]
Not sure what your purpose with this issue is. Do want us to merge this or is it just an FYI?
If merge, please provide a PR instead.

But with the current state of your code a click on `Cancel` will make `ssh-askpass` to succeed (and allowing sudo or access to the ssh-key. I don't think that is what you had in mind.

**Comment by a-kohout** [comment]
I'm not sure if that change would break other use cases, hence I opened an issue.
Sudo will fail with exit code 1 when clicking cancel with this change, as expected and same as before. ssh-askpass just won't print the error message in the terminal. I didn't think about access to ssh-keys.
Redirecting stderr to null when invoking sudo -v will get rid of the error message as well.
