### ISSUE TITLE
HomeBrew warning/error on brew install

### ISSUE THREAD

**Issue by leouk** [theseal/ssh-askpass#20]
Hi,
Many thanks for this tap to solve the annoying git push problem from IDEs. When I installed following your instructions, my homebrew gave the following warning:

"
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/theseal/homebrew-ssh-askpass/Formula/ssh-askpass.rb:43:in `plist'
Please report this to the theseal/ssh-askpass tap!
"

and
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/theseal/homebrew-ssh-askpass/Formula/ssh-askpass.rb:48:in `caveats'
Please report this to the theseal/ssh-askpass tap!

Multiple times.

**Comment by simmel** [comment]
Do you want to earn magical internet points and submit a PR which fixes 
it? = )

**Comment by theseal** [comment]
@gyran have created a [PR in on the tap](https://github.com/theseal/homebrew-ssh-askpass/pull/12). We will take it from there. 

Anyway, thanks for your report.
