### ISSUE TITLE
Link from X11R6 directory for VSCode

### ISSUE THREAD

**Issue by trinkel** [theseal/ssh-askpass#40]
VS Code (and presumably other applications) seem to look for `ssh-askpass` in `/usr/X11R6/bin`. Linking from here to `/usr/local/bin/ssh-askpass` resolved the issue.

Resolution would be to add
```sudo ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin```
to the install instructions in README.md

This was tested using the Without _Homebrew/MacPorts_ instructions

**Comment by theseal** [comment]
Just installed `vscode` and I worked out of the box with ssh-askpass installed with Homebrew (and started as a service).

Remember to load the plist as stated in the instructions in order to setup the required environment variables.

**Comment by trinkel** [comment]
The difference here is that I don't use Homebrew or MacPorts. I have XCode is installed on two of the three Macs (varying age and OS versions) but not the third. XQuartz is installed on all of the computers. None of these three computers has/had a `/usr/X11R6/bin` directory.

One of the computers started life as Monterey, but was migrated from an older computer. Another started with an older OS (Probably Catalina?) and is upgraded to Monterey.

The following is what is available on an out-of-the-box Mac (tested on several computers including a demo at BestBuy):
```
local / % cd /usr

local /usr % ls -la X*
	lrwxr-xr-x  1 root  wheel  25 Feb  6 15:22 X11 -> ../private/var/select/X11
	lrwxr-xr-x  1 root  wheel  25 Feb  6 15:22 X11R6 -> ../private/var/select/X11

local /usr % ls -la ../private/var/select/X11
	ls: ../private/var/select/X11: No such file or directory

local /usr % ls -la /usr/X11R6/bin
	ls: /usr/X11R6/bin: No such file or directory
```
This syncs with my three Macs. On the one Mac that I have installed ssh-askpass I get:

```
local /usr % ls -la ../private/var/select/X11
	lrwxr-xr-x   1 root  wheel      X11 -> /opt/X11
```

In all honesty, I don't recall if I made this link or if something else did.


VSCode, unless there's some way to change it, looks for `ssh-askpass` in `/usr/X11R6/bin` (or at least that's what I glean from the error message). Ultimately, that ends up being `/opt/X11/bin`. If that directory doesn't exist, you get the VSCode error. This may be more of a "if you get this error, create these links" sort of instruction:

```
ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin
ln -s /opt/X11 /private/var/select/X11
```

From what I can tell, a Mac that doesn't have Homebrew, MacPorts or another application that has altered the default directories, these two links need to be created for ssh-askpass


As a sidebar: I could create a pull request and add an install script for the _Without Homebrew/MacPorts_ version of the installation instructions if you are interested.

**Comment by theseal** [comment]
But even if you don't install via a package manager you can still "install" the plist provided by the project which will solve this issue.

**Comment by timrinkel** [comment]
Sorry, I meant to mention that I did install the plist. Glancing through the file I see the references to the ssh-askpass location. I will try it again at work today to see if I just screwed something up.

**Comment by trinkel** [comment]
Hmmmmm.

My sincere apologies. I went back to the installation and it now works without the link. I swear I copied and loaded the plist file the first time, but I obviously screwed something up along the way.

It is working well now.

**Comment by simmel** [comment]
No worries! It took a long time until @gaelicWizard came along and got that fixed for us = )
