### ISSUE TITLE
Keychain support

### ISSUE THREAD

**Issue by imcvampire** [theseal/ssh-askpass#42]
Is there any plan for adding support for storing passphrase/pin/... in Keychain?

**Comment by imcvampire** [comment]
@huyz. Not really. I'm using yubikey with ssh key in Fido, which is not supported by Apple ssh and openssh doesn't support keychain.

**Comment by simmel** [comment]
Sorry for the late reply!

As @huyz says this is something for ssh-add(1) to support which falls on Apple and OpenSSH.
